version: '2'
services:
  mongo:
    image: mongo:latest
    hostname: "mongo"
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    command: mongod

  api:
    build: .
    container_name: "conferences-app-api"
    restart: always
    ports:
      - 9000:9000
    expose:
      - 9000
    links:
      - mongo
    depends_on:
      - mongo